using Oxide.Game.Rust.Cui;
using UnityEngine;

// Code generated by Figma to Rust UI Exporter

var Overlay = new CuiElement
{
  Name = "Overlay",
  Parent = "Overlay",
  RectTransform = {
    AnchorMin = new Vector2(0, 0),
    AnchorMax = new Vector2(1, 1),
    OffsetMin = "0 0",
    OffsetMax = "1920 1080"
  },
  Image = {
    Color = "26 26 26 204"
  }
};

var Background = new CuiElement
{
  Name = "Background",
  Parent = Overlay,
  RectTransform = {
    AnchorMin = new Vector2(0, 0),
    AnchorMax = new Vector2(1, 1),
    OffsetMin = "0 0",
    OffsetMax = "1920 1080"
  },
  Image = {
    Color = "26 26 26 204"
  }
};

var Header = new CuiElement
{
  Name = "Header",
  Parent = Overlay,
  RectTransform = {
    AnchorMin = new Vector2(0, 1),
    AnchorMax = new Vector2(1, 1),
    OffsetMin = "0 -80",
    OffsetMax = "1920 0"
  },
  Image = {
    Color = "51 51 51 255"
  }
};

var Title = new CuiElement
{
  Name = "Title",
  Parent = Header,
  RectTransform = {
    AnchorMin = new Vector2(0.5, 0.5),
    AnchorMax = new Vector2(0.5, 0.5),
    OffsetMin = "-100 -15",
    OffsetMax = "100 15"
  },
  Text = {
    Text = "Мой интерфейс",
    FontSize = 18,
    Align = TextAnchor.MiddleCenter,
    Color = "255 255 255 1"
  },
};

var Button = new CuiElement
{
  Name = "Button",
  Parent = Overlay,
  RectTransform = {
    AnchorMin = new Vector2(0.5, 0.5),
    AnchorMax = new Vector2(0.5, 0.5),
    OffsetMin = "-150 -30",
    OffsetMax = "150 30"
  },
  Image = {
    Color = "51 153 204 255"
  }
};

var ButtonText = new CuiElement
{
  Name = "Button Text",
  Parent = Button,
  RectTransform = {
    AnchorMin = new Vector2(0, 0),
    AnchorMax = new Vector2(1, 1),
    OffsetMin = "0 0",
    OffsetMax = "0 0"
  },
  Text = {
    Text = "Нажми меня",
    FontSize = 16,
    Align = TextAnchor.MiddleCenter,
    Color = "255 255 255 1"
  },
};


private void CreateUI(BasePlayer player)
{
    var elements = new CuiElementContainer();
    elements.Add(Overlay);
    elements.Add(Background);
    elements.Add(Header);
    elements.Add(Title);
    elements.Add(Button);
    elements.Add(ButtonText);
    CuiHelper.AddUi(player, elements);
}


private void DestroyUI(BasePlayer player)
{
    CuiHelper.DestroyUi(player, "Overlay");
} 